// Mocks generated by Mockito 5.1.0 from annotations
// in e_commers/test/Service/user_services_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:e_commers/Models/Response/response_default.dart' as _i2;
import 'package:e_commers/Models/Response/response_user.dart' as _i3;
import 'package:e_commers/Service/user_services.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponseDefault_0 extends _i1.Fake implements _i2.ResponseDefault {}

class _FakeUser_1 extends _i1.Fake implements _i3.User {}

/// A class which mocks [UserServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserServices extends _i1.Mock implements _i4.UserServices {
  MockUserServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ResponseDefault> addNewUser(
          String? username, String? email, String? password) =>
      (super.noSuchMethod(
              Invocation.method(#addNewUser, [username, email, password]),
              returnValue:
                  Future<_i2.ResponseDefault>.value(_FakeResponseDefault_0()))
          as _i5.Future<_i2.ResponseDefault>);
  @override
  _i5.Future<_i3.User> getUserById() =>
      (super.noSuchMethod(Invocation.method(#getUserById, []),
              returnValue: Future<_i3.User>.value(_FakeUser_1()))
          as _i5.Future<_i3.User>);
  @override
  _i5.Future<_i2.ResponseDefault> updatePictureProfile(String? image) =>
      (super.noSuchMethod(Invocation.method(#updatePictureProfile, [image]),
              returnValue:
                  Future<_i2.ResponseDefault>.value(_FakeResponseDefault_0()))
          as _i5.Future<_i2.ResponseDefault>);
  @override
  _i5.Future<_i2.ResponseDefault> updateInformationUser(String? name,
          String? last, String? phone, String? address, String? reference) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateInformationUser, [name, last, phone, address, reference]),
          returnValue: Future<_i2.ResponseDefault>.value(
              _FakeResponseDefault_0())) as _i5.Future<_i2.ResponseDefault>);
  @override
  _i5.Future<_i2.ResponseDefault> updateStreetAddress(
          String? address, String? reference) =>
      (super.noSuchMethod(
              Invocation.method(#updateStreetAddress, [address, reference]),
              returnValue:
                  Future<_i2.ResponseDefault>.value(_FakeResponseDefault_0()))
          as _i5.Future<_i2.ResponseDefault>);
}
